config/routes.rb
ToyRails::Application.routes.draw do
  resources :toys
  root :to => 'toys#index'
end

app/models/toy.rb
class Toy < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  # GET /toys
  # GET /toys.json
  def index
    @toys = Toy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @toys }
    end
  end

  # GET /toys/1
  # GET /toys/1.json
  def show
    @toy = Toy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @toy }
    end
  end

  # GET /toys/new
  # GET /toys/new.json
  def new
    @toy = Toy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @toy }
    end
  end

  # GET /toys/1/edit
  def edit
    @toy = Toy.find(params[:id])
  end

  # POST /toys
  # POST /toys.json
  def create
    @toy = Toy.new(params[:toy])

    respond_to do |format|
      if @toy.save
        format.html { redirect_to @toy, notice: 'Toy was successfully created.' }
        format.json { render json: @toy, status: :created, location: @toy }
      else
        format.html { render action: "new" }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /toys/1
  # PUT /toys/1.json
  def update
    @toy = Toy.find(params[:id])

    respond_to do |format|
      if @toy.update_attributes(params[:toy])
        format.html { redirect_to @toy, notice: 'Toy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toys/1
  # DELETE /toys/1.json
  def destroy
    @toy = Toy.find(params[:id])
    @toy.destroy

    respond_to do |format|
      format.html { redirect_to toys_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToyRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/toys/_form.html.erb
<%= form_for(@toy) do |f| %>
  <% if @toy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@toy.errors.count, "error") %> prohibited this toy from being saved:</h2>

      <ul>
      <% @toy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/toys/edit.html.erb
<h1>Editing toy</h1>

<%= render 'form' %>

<%= link_to 'Show', @toy %> |
<%= link_to 'Back', toys_path %>

app/views/toys/index.html.erb
<h1>Listing toys</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @toys.each do |toy| %>
  <tr>
    <td><%= toy.name %></td>
    <td><%= toy.description %></td>
    <td><%= link_to 'Show', toy %></td>
    <td><%= link_to 'Edit', edit_toy_path(toy) %></td>
    <td><%= link_to 'Destroy', toy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Toy', new_toy_path %>

app/views/toys/new.html.erb
<h1>New toy</h1>

<%= render 'form' %>

<%= link_to 'Back', toys_path %>

app/views/toys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @toy.name %>
</p>

<p>
  <b>Description:</b>
  <%= @toy.description %>
</p>


<%= link_to 'Edit', edit_toy_path(@toy) %> |
<%= link_to 'Back', toys_path %>